[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/thanks"
  to = "/thanks/"
  status = 301

[[redirects]]
  from = "/gracias"
  to = "/thanks/"
  status = 301

[[redirects]]
  from = "/gracias/"
  to = "/thanks/"
  status = 301

[build.environment]
  NODE_VERSION = "22"
